# batch_size : 50 #5000
# n_steps : 400
# every : 50
# n_chunks : 8
# train_size : 5000
# sigma : 0.05
# random_seed : 42
batch_size: &batch_size 1000
n_steps: &n_steps 1000
burn_in: &burn_in 100

min_dim: 5 #10
max_dim: 40
step_dim: 5
plot_dims: [5, 10, 20, 40] #12
d1: 0
d2: 1
xlim: [-3, 3]
ylim: [-3, 3]


loc_1_target : -1.0
loc_1_nonzero: 1
loc_2_target : 1.0
loc_2_nonzero: 1
scale_target : 0.3 #1.0
scale_proposal : 1.0 #2
loc_proposal : 0


device: cpu
figpath: figs/2_gaussians
respath: dump

methods:
  i-SIR:
    n_steps : *n_steps
    burn_in : *burn_in
    mcmc_class: CISIR
    params:
      N: 10
    # every : 100
    color : "tab:blue"
    batch_size: *batch_size

  # CISIR:
  #   mcmc_class: CISIR
  #   params:
  #     N: 10
  #     corr_coef: 0.9
  #     bernoulli_prob_corr: 0.5
  #     n_steps : 1000
  #   # every : 100
  #   color : "tab:orange"

  # ULA:
  #   mcmc_class: ULA
  #   params:
  #     grad_step: 0.001
  #     noise_scale: 0.045
  #     n_steps : 800
  #   every : 100
  #   color : "tab:brown"

  MALA:
    mcmc_class: MALA
    n_steps : *n_steps
    burn_in : *burn_in
    params:
      grad_step: 0.01
      adapt_stepsize: True
    # every : 100
    color : "tab:green"
    batch_size: *batch_size

  "Ex$^2$MCMC":
    mcmc_class: Ex2MCMC
    n_steps : *n_steps
    burn_in : *burn_in
    params:
      N: 10
      grad_step: 0.01
      adapt_stepsize: True
      corr_coef: 0.9
      bernoulli_prob_corr: 0.5
      mala_steps: 1
    # every : 100
    color : "tab:red"
    batch_size: *batch_size


  "Ex$^2$MCMC no ind.":
    mcmc_class: Ex2MCMC
    n_steps : *n_steps
    burn_in : *burn_in
    params:
      N: *batch_size
      grad_step: 0.01
      adapt_stepsize: True
      corr_coef: 0.95
      bernoulli_prob_corr: 0.9
      mala_steps: 1
      ind_chains: False
    # every : 100
    color : "tab:purple"
    batch_size: 1


        # "Ex$^2$MCMC w/o corr":
        #   mcmc_class: Ex2MCMC
        #   params:
        #     N: 5
        #     grad_step: 0.01
        #     adapt_stepsize: True
        #     mala_steps: 1
        #     n_steps : 800
        #   every : 100
        #   color : "tab:purple"

        # FlCISIR:
        #   mcmc_class: CISIR
        #   params:
        #     N: 5
        #     corr_coef: 0.9
        #     bernoulli_prob_corr: 0.5
        #   flow:
        #     num_flows: 4
        #     lr: 0.01
        #     batch_size: 100
        #     n_steps: 200

  # FlEx$^2$MCMC:
  #   mcmc_class: Ex2MCMC
  #   n_steps : 1000
  #   params:
  #     N: 10
  #     grad_step: 0.01
  #     adapt_stepsize: True
  #     corr_coef: 0.9
  #     bernoulli_prob_corr: 0.5
  #     mala_steps: 1
  #   flow:
  #     num_flows: 2
  #     lr: 0.01
  #     batch_size: 100
  #     n_steps: 200
  #   color: "tab:pink"
