batch_size : &batch_size 10000 #20000
train_size : *batch_size
sigma : 0.05
random_seed : null #42
multistart: true
n_eval: 10

alpha: 1 #2 #1.3

device: cpu
figpath: figs/gan_gaussians_2d_multi
respath: dump
data_root: data

trunc_chain_len: 2000
burn_in: &burn_in 0 #10 #0
n_steps: &n_steps 1000
every: &every 1000
n_chunks : 1 #10

methods:
  ULA_0.01:
    mcmc_class: ULA
    params:
      grad_step: 0.01 #001
      #noise_scale: 0.01
    burn_in : *burn_in
    n_steps : *n_steps
    every : *every
    color : "tab:brown"

  ULA_0.1:
    mcmc_class: ULA
    params:
      grad_step: 0.1 #001
      #noise_scale: 0.01
    burn_in : *burn_in
    n_steps : *n_steps
    every : *every
    color : "tab:brown"

  ULA_1:
    mcmc_class: ULA
    params:
      grad_step: 1 #001
      #noise_scale: 0.01
    burn_in : *burn_in
    n_steps : *n_steps
    every : *every
    color : "tab:brown"

  # MALA:
  #   mcmc_class: MALA
  #   params:
  #     grad_step: 0.001
  #     noise_scale: 0.01
  #     adapt_stepsize: False
  #   burn_in : *burn_in
  #   n_steps : *n_steps
  #   every : *every
  #   color : "tab:green"

  # Ex$^2$MCMC:
  #   mcmc_class: Ex2MCMC
  #   params:
  #     N: 5
  #     grad_step: 0.001
  #     noise_scale: 0.01
  #     adapt_stepsize: False
  #     corr_coef: 0.99
  #     bernoulli_prob_corr: 1.0 #0.5 #0.5
  #     mala_steps: 1
  #   burn_in : *burn_in
  #   n_steps : *n_steps
  #   every : *every
  #   color : "tab:red"
